version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: appverse-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: 86400000
    ports:
      - "8081:8081"

  app-service:
    build: ./app-service
    container_name: app-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      AI_SERVICE_BASE_URL: http://ai-service:8001
    ports:
      - "8082:8082"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    depends_on:
      - user-service
      - app-service
    ports:
      - "8080:8080"

  # AI service later
  ai-service:
    build: ./ai-service
    container_name: ai-service
    ports:
      - "8001:8001"

volumes:
  mysql_data:
